#!/bin/sh
# autotun browser shim — opens a URL on the machine running autotun instead of
# on this host.
#
# Regenerated by autotun every session; the socket and nonce below belong to
# the session that wrote it. Safe to delete, and safe to leave in $BROWSER
# forever: with no autotun listening this falls through to whatever this box
# would have done on its own.

sock='@SOCKET@'
nonce='@NONCE@'
bindir='@BINDIR@'

# `gio open URL`, which some desktop stacks use in place of xdg-open.
if [ "$1" = "open" ] && [ -n "$2" ]; then
	shift
fi
url=$1

# relay hands the URL to autotun and echoes its answer. Dev boxes vary in
# which of these they have, and none of them is guaranteed, so try in order of
# how likely each is to be installed rather than how pretty it is.
relay() {
	if command -v nc >/dev/null 2>&1; then
		printf '%s %s\n' "$nonce" "$url" | nc -U "$sock" 2>/dev/null
	elif command -v socat >/dev/null 2>&1; then
		printf '%s %s\n' "$nonce" "$url" | socat -t5 - "UNIX-CONNECT:$sock" 2>/dev/null
	elif command -v python3 >/dev/null 2>&1; then
		python3 -c 'import socket,sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(10)
s.connect(sys.argv[1])
s.sendall((sys.argv[2] + " " + sys.argv[3] + "\n").encode())
sys.stdout.write(s.recv(256).decode("utf-8", "replace"))' "$sock" "$nonce" "$url" 2>/dev/null
	else
		return 1
	fi
}

if [ -n "$url" ] && [ -S "$sock" ]; then
	case $(relay) in
	ok*) exit 0 ;;
	esac
fi

# No autotun, or it declined. Drop our own directory from PATH so the fallback
# finds the real opener rather than this script again.
clean=""
IFS=:
for dir in $PATH; do
	[ "$dir" = "$bindir" ] && continue
	clean="${clean:+$clean:}$dir"
done
unset IFS
PATH=$clean
export PATH

for opener in xdg-open sensible-browser x-www-browser www-browser; do
	if command -v "$opener" >/dev/null 2>&1; then
		exec "$opener" "$url"
	fi
done

echo "autotun: no session listening on $sock; open this yourself:" >&2
echo "  $url" >&2
exit 1
